# Generated by Django 4.0.3 on 2022-03-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_postphoto_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphoto',
            name='author',
        ),
    ]
