# Generated by Django 4.0.3 on 2022-03-21 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0008_alter_postphoto_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='postphoto_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
