# Generated by Django 4.0.3 on 2022-03-22 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0009_alter_postphoto_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postphoto',
            name='views',
            field=models.ManyToManyField(related_name='postphoto_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
