# Generated by Django 4.0.3 on 2022-03-22 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0010_postphoto_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='postphoto',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='like',
            field=models.ManyToManyField(related_name='postvideo_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='views',
            field=models.ManyToManyField(related_name='postvideo_view', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postphoto',
            name='like',
            field=models.ManyToManyField(related_name='postphoto_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
