# Generated by Django 4.0.3 on 2022-03-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_photocomment_post_alter_videocomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
