# Generated by Django 4.0.3 on 2022-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_photocomment_date_videocomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
