# Generated by Django 4.0.3 on 2022-03-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_photocomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
