# Generated by Django 4.0.3 on 2022-03-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_alter_photocomment_date_alter_videocomment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocomment',
            old_name='post',
            new_name='postvideo',
        ),
    ]
