# Generated by Django 4.0.3 on 2022-03-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_rename_post_videocomment_postvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocomment',
            old_name='comment',
            new_name='videocomment',
        ),
    ]
