# Generated by Django 4.0.3 on 2022-03-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_rename_comment_videocomment_videocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='postvideo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocomments', to='gallery.postvideo'),
        ),
    ]
