# Generated by Django 4.0.3 on 2022-03-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_alter_photocomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
